name: CI DevOps 2024
on:
  push:
    branches:
      - main    # Run on pushes to main
      - develop # Run on pushes to develop
  pull_request:

jobs:
  test-backend:
    runs-on: ubuntu-22.04
    steps:
      # Step 1: Checkout the repository
      - name: Check out the repository
        uses: actions/checkout@v2.5.0

      # Step 2: Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'amazon-corretto'

      # Step 3: Build and test the application
      - name: Build and test with Maven
        run: mvn clean verify